# General Plugin Information
name: Turrets
main: me.azazad.turrets.TurretsPlugin
version: 0.2.4
author: wristdirect
database: false
softdepend: [ Factions ]

# Commands
commands:
   turrets:
      aliases: [tur]


permissions:
  turrets.*:
    description: Gives access to all Turrets permissions.
    children:
      turrets.activate: true
      turrets.reload: true
      turrets.addturret: true
      turrets.destroyturret: true
      turrets.manturret: true
      turrets.setammousage: true
      turrets.setammotype: true
      turrets.ignoremaxturrets: true
      turrets.config: true
      turrets.modwblists: true
      turrets.modotherwblists: true
      turrets.modgloballists: true
      turrets.loadsave: true
    turrets.activate: 
      description: Allows user to activate/deactivate turrets.
      default: true
    turrets.addturret:
      description: Allows user to create a new turret.
      default: true
    turrets.destroyturret: 
      description: Allows user to destroy a turret.
      default: true
    turrets.manturret:
      description: Allows user to man a turret.
      default: true
      turrets.setammousage: 
      description: Allows user to change the ammo usage of a turret.
      default: op
    turrets.setammotype:
      description: Allows user to change ammo type of a turret.
      default: op
    turrets.ignoremaxturrets: 
      description: Allows user to ignore the maxTurretsPerPlayer config setting.
      default: op
    turrets.config: 
      description: Allows user to change config options in-game.
      default: op
    turrets.modwblists:
      description: If true, allows user to modify their own whitelist and blacklist for their turrets.
      default: true
    turrets.modotherwblists:
      description: If true, allows user to modify others' whitelists and blacklists.
      default: op
    turrets.modgloballists:
      description: If true, allows user to modify the global whitelist and blacklist.
      default: op
    turrets.loadsave.*:
      description: Gives access to loading and saving commands.
      children: 
        turrets.loadsave.save: true
        turrets.loadsave.reload: true
      turrets.loadsave.reload: 
        description: Allows user to reload the Turrets plugin. Often necessary for all turrets to load.
        default: op
      turrets.loadsave.save: 
        description: Allows user to save all Turrets to the database.
        default: op
        